---
server:
  port: 9996
  mode: mock
log:
  logFile: /home/zhoushx/batchSendHtdf/addr0/log/batch.log

  #logLevel  : 1, Alert; 2, Crit; 3, Error; 4, Warn; 5, Notice; 6, Info; 7, Debug
  logLevel: 7

...
